# Generated by Django 3.2.3 on 2021-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='wand_length',
            field=models.FloatField(default=0.0),
        ),
    ]
