# Generated by Django 3.2.3 on 2021-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_card_wand_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='wand_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
