# Generated by Django 3.2.3 on 2021-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house',
            field=models.CharField(choices=[('G', 'Gryffindor'), ('H', 'Hufflepuff'), ('R', 'Ravenclaw'), ('S', 'Slytherin'), ('U', 'undefined')], default='U', max_length=40),
        ),
    ]
